version: "3"
services:
  app:
    build:
     context: .
     dockerfile: docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: yarn serve
    env_file: .env
    ports:
      - "3000:8080"
